backend:
  name: github 
  repo: Jason-Jay-Mason/jasonmasondev
  base_url: https://www.jasonmason.dev
  branch: main 
  auth_endpoint: api/auth
local_backend: false
publish_mode: editorial_workflow
media_folder: static/
public_folder: /
site_url: https://www.jasonmason.dev
display_url:  https://www.jasonmason.dev
editor:
  preview: false
collections:
  - name: project
    extension: json
    label: Projects 
    label_singular: Project 
    folder: src/content/projects/
    create: true
    slug: '{{slug}}'
    preview_path: '/projects/{{slug}}'
    identifier_field: slug 
    fields:
      - {name: slug, label: Slug, widget: string}
      - name: headline
        label: Headline
        widget: object
        fields:
          - {name: sub, label: Sub Headline, widget: string}
          - {name: main, label: Main Headline, widget: string}
      - {name: body, label: Body, widget: text}
      - name: cta
        label: CTA
        widget: object
        fields:
          - {name: innerText, label: Inner Text, widget: string}
          - {name: href, label: Href, widget: string}
      - {name: githubHref, label: Github Href, required: false, widget: string}
      - {name: year, label: Year, widget: number}
      - name: img
        label: Image
        widget: object
        fields:
          - {name: src, label: Image Source, widget: image}
          - {name: alt, label: Alt Text, widget: string}
      - name: tags
        label: Tags
        widget: list
  - name: company-page 
    extension: json
    label: Company Pages
    label_singular: Company Page
    folder: src/content/company-pages/
    create: true
    slug: '{{slug}}'
    preview_path: '/{{slug}}'
    identifier_field: slug 
    fields:
      - {name: slug, label: Slug, widget: string}
      - name: company
        label: Company
        widget: object
        fields:
          - {name: name, label: Company Name, widget: string }
          - {name: logoSrc, label: Company Logo, widget: image, choose_url: true}
      - name: layout
        label: Layout
        widget: object
        fields:
          - name: links
            label: Links
            label_singular: Link
            widget: list
            fields:
              - {name: innerText, label: Inner Text, widget: string}
              - {name: href, label: Href, widget: string}
      - name: hero
        label: Hero
        widget: object
        fields:
          - {name: hook, label: Hook, widget: string}
          - name: cta
            label: CTA
            widget: object
            fields:
              - {name: isVideo, label: Video, widget: boolean}
              - {name: hrefOrSrc, label: Href (or Src), widget: string}
              - {name: innerText, label: Inner Text, widget: string}
      - name: coverLetter
        label: Cover Letter 
        widget: object 
        fields:
          - name: headline 
            label: Headline
            widget: object
            fields:
              - {name: sub, label: Sub Headline, widget: string}
              - {name: main, label: Main Headline, widget: string}
          - {name: body, label: Body, widget: text}
      - name: profile
        label: Profile
        widget: object
        fields:
          - name: headline
            label: Headline
            widget: object
            fields:
              - {name: sub, label: Sub Headline, widget: string}
              - {name: main, label: Main Headline, widget: string}
          - {name: body, label: Body, widget: text}
          - name: interests
            label: interests
            widget: list
            fields: 
              - {name: title, label: Title, widget: string }
              - {name: iconSrc, label: Icon, widget: image}
          - name: img
            label: Image
            widget: object
            fields:
              - {name: alt, label: Alt Text, widget: string}
              - {name: src, label: Image, widget: image}
      - name: experience
        label: Experience
        widget: object
        fields: 
          - name: headline
            label: Headline
            widget: object
            fields:
              - {name: sub, label: Sub Headline, widget: string}
              - {name: main, label: Main Headline, widget: string}
          - name: records
            label: Experiences
            widget: list
            fields:
              - {name: startYear, label: Start Year, widget: number}
              - {name: endYear, label: End Year, widget: number}
              - name: headline
                label: Headline
                widget: object
                fields:
                  - {name: sub, label: Sub Headline, widget: string}
                  - {name: main, label: Main Headline, widget: string}
              - {name: description, label: Description, widget: text}
              - name: fadeIn
                label: Animation Fade In
                widget: object
                fields:
                  - {name: start, label: Start, widget: number }
                  - {name: length, label: Length, widget: number }
                  - {name: startValue, label: Start Value, widget: number }
                  - {name: endValue, label: End Value, widget: number }
          - name: skills
            label: Skills
            widget: list
            fields:
              - {name: title, label: Title, widget: string}
              - name: growth
                label: Growth Animation
                widget: list
                fields:
                  - {name: startValue, label: Start Value, widget: number}
                  - {name: endValue, label: End Value, widget: number}
      - name: portfolio 
        label: Portfolio
        widget: object
        fields:
          - name: headline 
            label: headline
            widget: object
            fields:
              - {name: sub, label: Sub Headline, widget: string}
              - {name: main, label: Main Headline, widget: string}


                



          


